services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'kv1.me'
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./www:/var/www
      - ./fs/etc/nginx/conf.d/kv1.me.conf:/etc/nginx/conf.d/kv1.me.conf
    ports:
      - 443:443
      - 80:80

volumes:
  ssl_data: