
server {
    listen                80;
    listen                443 ssl;
    server_name           kv1.me;

    include resty-server-https.conf;

    index                 index.html;

    location /.well-known/acme-challenge/ {
        auth_basic off;
        content_by_lua_block {
            auto_ssl:challenge_server()
        }
    }

    location = /health {
        access_log off;
        return 204;
    }

    location = /home {
        return 301 /home/;
    }

    location ^~ /home/ {
        root /var/www;
        try_files $uri $uri/ =404;
    }

    location = /metrics/data.json {
        root /var/www;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        add_header Surrogate-Control "no-store" always;

        try_files /metrics/data.json =404;
    }

    location ^~ /metrics/ {
        root /var/www;
        try_files $uri $uri/ =404;
    }

    location / {
        root /var/www/business-card;
        try_files $uri $uri/ =404;
    }
}
